---
kind: pipeline
type: docker
name: arm64 Image

platform:
  os: linux
  arch: arm64

steps:
  - name: imagebuild
    image: plugins/docker
    settings:
      repo: svil/ansible
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    tags: latest-linux-arm64
---
kind: pipeline
type: docker
name: amd64 Image

platform:
  os: linux
  arch: amd64

steps:
  - name: imagebuild
    image: plugins/docker
    settings:
      repo: svil/ansible
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    tags: latest-linux-amd64
---
kind: pipeline
type: docker
name: push manifest

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      target: svil/ansible:latest
      template: svil/ansible:latest-OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
depends_on:
  - arm64 Image
  - amd64 Image
